/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Content = IDL.Record({
  'id' : IDL.Text,
  'media' : ExternalBlob,
  'contentType' : IDL.Text,
  'value' : IDL.Text,
  'page' : IDL.Text,
});
export const DropInClass = IDL.Record({
  'id' : IDL.Text,
  'instructor' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Nat64,
  'level' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'currency' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const ResidentialCourse = IDL.Record({
  'id' : IDL.Text,
  'isPrivateAvailable' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'monthlyDates' : IDL.Vec(IDL.Text),
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Retreat = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : IDL.Nat64,
  'description' : IDL.Text,
  'availability' : IDL.Nat,
  'currency' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'startDate' : IDL.Nat64,
});
export const RetreatPackage = IDL.Record({
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'price' : IDL.Nat,
  'roomType' : IDL.Text,
});
export const RetreatWithPackages = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'ctaWhatsapp' : IDL.Text,
  'endDate' : IDL.Nat64,
  'packages' : IDL.Vec(RetreatPackage),
  'isCustomizable' : IDL.Bool,
  'hasRecurringDates' : IDL.Bool,
  'overview' : IDL.Text,
  'description' : IDL.Text,
  'inclusions' : IDL.Text,
  'ctaBook' : IDL.Text,
  'image' : ExternalBlob,
  'location' : IDL.Text,
  'itinerary' : IDL.Text,
  'startDate' : IDL.Nat64,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Nat64,
  'author' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});
export const VideoCourse = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'videoFiles' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'itemId' : IDL.Text,
  'userId' : IDL.Principal,
  'bookingDate' : IDL.Nat64,
  'currency' : IDL.Text,
  'itemType' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PayPalPaymentResponse = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'paymentId' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const RazorpayPaymentRequest = IDL.Record({
  'receipt' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'purchaseHistory' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'googleBusinessLink' : IDL.Text,
  'socialLinks' : IDL.Record({
    'instagram' : IDL.Text,
    'facebook' : IDL.Text,
    'youtube' : IDL.Text,
  }),
  'whatsapp' : IDL.Text,
  'googleMapsLink' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PayPalConfig = IDL.Record({
  'clientId' : IDL.Text,
  'testMode' : IDL.Bool,
  'enabled' : IDL.Bool,
  'callbackUrl' : IDL.Text,
  'clientSecret' : IDL.Text,
});
export const RazorpayConfig = IDL.Record({
  'testMode' : IDL.Bool,
  'enabled' : IDL.Bool,
  'apiKey' : IDL.Text,
  'apiSecret' : IDL.Text,
  'callbackUrl' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PayPalVerificationResponse = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const RazorpayVerificationResponse = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'paymentId' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContent' : IDL.Func([Content], [], []),
  'addDropInClass' : IDL.Func([DropInClass], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addResidentialCourse' : IDL.Func([ResidentialCourse], [], []),
  'addRetreat' : IDL.Func([Retreat], [], []),
  'addRetreatPackage' : IDL.Func([IDL.Text, IDL.Vec(RetreatPackage)], [], []),
  'addRetreatWithPackages' : IDL.Func([RetreatWithPackages], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'addVideoCourse' : IDL.Func([VideoCourse], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookDropInClass' : IDL.Func([Booking], [], []),
  'bookRetreat' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPayPalPaymentRequest' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [PayPalPaymentResponse],
      [],
    ),
  'createRazorpayPaymentRequest' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
      [RazorpayPaymentRequest],
      [],
    ),
  'deleteContent' : IDL.Func([IDL.Text], [], []),
  'deleteDropInClass' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteResidentialCourse' : IDL.Func([IDL.Text], [], []),
  'deleteRetreat' : IDL.Func([IDL.Text], [], []),
  'deleteRetreatPackage' : IDL.Func([IDL.Text], [], []),
  'deleteRetreatWithPackages' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'deleteVideoCourse' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllRetreatsWithPackages' : IDL.Func(
      [],
      [IDL.Vec(RetreatWithPackages)],
      ['query'],
    ),
  'getBookingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getContentByPage' : IDL.Func([IDL.Text], [IDL.Vec(Content)], ['query']),
  'getDropInClasses' : IDL.Func([], [IDL.Vec(DropInClass)], ['query']),
  'getHomePageFeaturedRetreats' : IDL.Func([], [IDL.Vec(Retreat)], ['query']),
  'getPayPalConfig' : IDL.Func([], [IDL.Opt(PayPalConfig)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
  'getResidentialCourses' : IDL.Func(
      [],
      [IDL.Vec(ResidentialCourse)],
      ['query'],
    ),
  'getRetreatPackages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RetreatPackage)))],
      ['query'],
    ),
  'getRetreatWithPackages' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RetreatWithPackages)],
      ['query'],
    ),
  'getRetreats' : IDL.Func([], [IDL.Vec(Retreat)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoCourses' : IDL.Func([], [IDL.Vec(VideoCourse)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPayPalEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseProduct' : IDL.Func([Booking], [], []),
  'purchaseVideoCourse' : IDL.Func([Booking], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeaturedRetreats' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setPayPalConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'setRazorpayConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateContent' : IDL.Func([Content], [], []),
  'updateDropInClass' : IDL.Func([DropInClass], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateResidentialCourse' : IDL.Func([ResidentialCourse], [], []),
  'updateRetreat' : IDL.Func([Retreat], [], []),
  'updateRetreatPackage' : IDL.Func(
      [IDL.Text, IDL.Vec(RetreatPackage)],
      [],
      [],
    ),
  'updateRetreatWithPackages' : IDL.Func([RetreatWithPackages], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
  'updateVideoCourse' : IDL.Func([VideoCourse], [], []),
  'verifyPayPalPayment' : IDL.Func(
      [IDL.Text],
      [PayPalVerificationResponse],
      [],
    ),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [RazorpayVerificationResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Content = IDL.Record({
    'id' : IDL.Text,
    'media' : ExternalBlob,
    'contentType' : IDL.Text,
    'value' : IDL.Text,
    'page' : IDL.Text,
  });
  const DropInClass = IDL.Record({
    'id' : IDL.Text,
    'instructor' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Nat64,
    'level' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'currency' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const ResidentialCourse = IDL.Record({
    'id' : IDL.Text,
    'isPrivateAvailable' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'monthlyDates' : IDL.Vec(IDL.Text),
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Retreat = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : IDL.Nat64,
    'description' : IDL.Text,
    'availability' : IDL.Nat,
    'currency' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'startDate' : IDL.Nat64,
  });
  const RetreatPackage = IDL.Record({
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'price' : IDL.Nat,
    'roomType' : IDL.Text,
  });
  const RetreatWithPackages = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'ctaWhatsapp' : IDL.Text,
    'endDate' : IDL.Nat64,
    'packages' : IDL.Vec(RetreatPackage),
    'isCustomizable' : IDL.Bool,
    'hasRecurringDates' : IDL.Bool,
    'overview' : IDL.Text,
    'description' : IDL.Text,
    'inclusions' : IDL.Text,
    'ctaBook' : IDL.Text,
    'image' : ExternalBlob,
    'location' : IDL.Text,
    'itinerary' : IDL.Text,
    'startDate' : IDL.Nat64,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Nat64,
    'author' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const VideoCourse = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'videoFiles' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'itemId' : IDL.Text,
    'userId' : IDL.Principal,
    'bookingDate' : IDL.Nat64,
    'currency' : IDL.Text,
    'itemType' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PayPalPaymentResponse = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'paymentId' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const RazorpayPaymentRequest = IDL.Record({
    'receipt' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'purchaseHistory' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'googleBusinessLink' : IDL.Text,
    'socialLinks' : IDL.Record({
      'instagram' : IDL.Text,
      'facebook' : IDL.Text,
      'youtube' : IDL.Text,
    }),
    'whatsapp' : IDL.Text,
    'googleMapsLink' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PayPalConfig = IDL.Record({
    'clientId' : IDL.Text,
    'testMode' : IDL.Bool,
    'enabled' : IDL.Bool,
    'callbackUrl' : IDL.Text,
    'clientSecret' : IDL.Text,
  });
  const RazorpayConfig = IDL.Record({
    'testMode' : IDL.Bool,
    'enabled' : IDL.Bool,
    'apiKey' : IDL.Text,
    'apiSecret' : IDL.Text,
    'callbackUrl' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PayPalVerificationResponse = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const RazorpayVerificationResponse = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'paymentId' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContent' : IDL.Func([Content], [], []),
    'addDropInClass' : IDL.Func([DropInClass], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addResidentialCourse' : IDL.Func([ResidentialCourse], [], []),
    'addRetreat' : IDL.Func([Retreat], [], []),
    'addRetreatPackage' : IDL.Func([IDL.Text, IDL.Vec(RetreatPackage)], [], []),
    'addRetreatWithPackages' : IDL.Func([RetreatWithPackages], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'addVideoCourse' : IDL.Func([VideoCourse], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookDropInClass' : IDL.Func([Booking], [], []),
    'bookRetreat' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPayPalPaymentRequest' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [PayPalPaymentResponse],
        [],
      ),
    'createRazorpayPaymentRequest' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
        [RazorpayPaymentRequest],
        [],
      ),
    'deleteContent' : IDL.Func([IDL.Text], [], []),
    'deleteDropInClass' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteResidentialCourse' : IDL.Func([IDL.Text], [], []),
    'deleteRetreat' : IDL.Func([IDL.Text], [], []),
    'deleteRetreatPackage' : IDL.Func([IDL.Text], [], []),
    'deleteRetreatWithPackages' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'deleteVideoCourse' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllRetreatsWithPackages' : IDL.Func(
        [],
        [IDL.Vec(RetreatWithPackages)],
        ['query'],
      ),
    'getBookingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getContentByPage' : IDL.Func([IDL.Text], [IDL.Vec(Content)], ['query']),
    'getDropInClasses' : IDL.Func([], [IDL.Vec(DropInClass)], ['query']),
    'getHomePageFeaturedRetreats' : IDL.Func([], [IDL.Vec(Retreat)], ['query']),
    'getPayPalConfig' : IDL.Func([], [IDL.Opt(PayPalConfig)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
    'getResidentialCourses' : IDL.Func(
        [],
        [IDL.Vec(ResidentialCourse)],
        ['query'],
      ),
    'getRetreatPackages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RetreatPackage)))],
        ['query'],
      ),
    'getRetreatWithPackages' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RetreatWithPackages)],
        ['query'],
      ),
    'getRetreats' : IDL.Func([], [IDL.Vec(Retreat)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoCourses' : IDL.Func([], [IDL.Vec(VideoCourse)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPayPalEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseProduct' : IDL.Func([Booking], [], []),
    'purchaseVideoCourse' : IDL.Func([Booking], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeaturedRetreats' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setPayPalConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'setRazorpayConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateContent' : IDL.Func([Content], [], []),
    'updateDropInClass' : IDL.Func([DropInClass], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateResidentialCourse' : IDL.Func([ResidentialCourse], [], []),
    'updateRetreat' : IDL.Func([Retreat], [], []),
    'updateRetreatPackage' : IDL.Func(
        [IDL.Text, IDL.Vec(RetreatPackage)],
        [],
        [],
      ),
    'updateRetreatWithPackages' : IDL.Func([RetreatWithPackages], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
    'updateVideoCourse' : IDL.Func([VideoCourse], [], []),
    'verifyPayPalPayment' : IDL.Func(
        [IDL.Text],
        [PayPalVerificationResponse],
        [],
      ),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [RazorpayVerificationResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };