/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'status' : string,
  'itemId' : string,
  'userId' : Principal,
  'bookingDate' : bigint,
  'currency' : string,
  'itemType' : string,
  'amount' : bigint,
}
export interface ContactInfo {
  'googleBusinessLink' : string,
  'socialLinks' : {
    'instagram' : string,
    'facebook' : string,
    'youtube' : string,
  },
  'whatsapp' : string,
  'googleMapsLink' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Content {
  'id' : string,
  'media' : ExternalBlob,
  'contentType' : string,
  'value' : string,
  'page' : string,
}
export interface DropInClass {
  'id' : string,
  'instructor' : string,
  'name' : string,
  'time' : bigint,
  'level' : string,
  'durationMinutes' : bigint,
  'currency' : string,
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface PayPalConfig {
  'clientId' : string,
  'testMode' : boolean,
  'enabled' : boolean,
  'callbackUrl' : string,
  'clientSecret' : string,
}
export interface PayPalPaymentResponse {
  'error' : [] | [string],
  'paymentId' : [] | [string],
  'success' : boolean,
}
export interface PayPalVerificationResponse {
  'error' : [] | [string],
  'success' : boolean,
  'transactionId' : [] | [string],
}
export interface Product {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'currency' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface RazorpayConfig {
  'testMode' : boolean,
  'enabled' : boolean,
  'apiKey' : string,
  'apiSecret' : string,
  'callbackUrl' : string,
}
export interface RazorpayPaymentRequest {
  'receipt' : string,
  'currency' : string,
  'amount' : bigint,
}
export interface RazorpayVerificationResponse {
  'error' : [] | [string],
  'paymentId' : [] | [string],
  'success' : boolean,
}
export interface ResidentialCourse {
  'id' : string,
  'isPrivateAvailable' : boolean,
  'name' : string,
  'description' : string,
  'currency' : string,
  'monthlyDates' : Array<string>,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Retreat {
  'id' : string,
  'title' : string,
  'endDate' : bigint,
  'description' : string,
  'availability' : bigint,
  'currency' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'startDate' : bigint,
}
export interface RetreatPackage {
  'description' : string,
  'currency' : string,
  'price' : bigint,
  'roomType' : string,
}
export interface RetreatWithPackages {
  'id' : string,
  'title' : string,
  'duration' : string,
  'ctaWhatsapp' : string,
  'endDate' : bigint,
  'packages' : Array<RetreatPackage>,
  'isCustomizable' : boolean,
  'hasRecurringDates' : boolean,
  'overview' : string,
  'description' : string,
  'inclusions' : string,
  'ctaBook' : string,
  'image' : ExternalBlob,
  'location' : string,
  'itinerary' : string,
  'startDate' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Testimonial {
  'id' : string,
  'date' : bigint,
  'author' : string,
  'message' : string,
  'rating' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'purchaseHistory' : Array<string>,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoCourse {
  'id' : string,
  'title' : string,
  'description' : string,
  'currency' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'videoFiles' : Array<ExternalBlob>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContent' : ActorMethod<[Content], undefined>,
  'addDropInClass' : ActorMethod<[DropInClass], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addResidentialCourse' : ActorMethod<[ResidentialCourse], undefined>,
  'addRetreat' : ActorMethod<[Retreat], undefined>,
  'addRetreatPackage' : ActorMethod<[string, Array<RetreatPackage>], undefined>,
  'addRetreatWithPackages' : ActorMethod<[RetreatWithPackages], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'addVideoCourse' : ActorMethod<[VideoCourse], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookDropInClass' : ActorMethod<[Booking], undefined>,
  'bookRetreat' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPayPalPaymentRequest' : ActorMethod<
    [Array<string>, bigint, string],
    PayPalPaymentResponse
  >,
  'createRazorpayPaymentRequest' : ActorMethod<
    [Array<string>, bigint, string, string],
    RazorpayPaymentRequest
  >,
  'deleteContent' : ActorMethod<[string], undefined>,
  'deleteDropInClass' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteResidentialCourse' : ActorMethod<[string], undefined>,
  'deleteRetreat' : ActorMethod<[string], undefined>,
  'deleteRetreatPackage' : ActorMethod<[string], undefined>,
  'deleteRetreatWithPackages' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'deleteVideoCourse' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllRetreatsWithPackages' : ActorMethod<[], Array<RetreatWithPackages>>,
  'getBookingsByUser' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getContentByPage' : ActorMethod<[string], Array<Content>>,
  'getDropInClasses' : ActorMethod<[], Array<DropInClass>>,
  'getHomePageFeaturedRetreats' : ActorMethod<[], Array<Retreat>>,
  'getPayPalConfig' : ActorMethod<[], [] | [PayPalConfig]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getRazorpayConfig' : ActorMethod<[], [] | [RazorpayConfig]>,
  'getResidentialCourses' : ActorMethod<[], Array<ResidentialCourse>>,
  'getRetreatPackages' : ActorMethod<
    [],
    Array<[string, Array<RetreatPackage>]>
  >,
  'getRetreatWithPackages' : ActorMethod<[string], [] | [RetreatWithPackages]>,
  'getRetreats' : ActorMethod<[], Array<Retreat>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoCourses' : ActorMethod<[], Array<VideoCourse>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPayPalEnabled' : ActorMethod<[], boolean>,
  'isRazorpayEnabled' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'purchaseProduct' : ActorMethod<[Booking], undefined>,
  'purchaseVideoCourse' : ActorMethod<[Booking], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeaturedRetreats' : ActorMethod<[Array<string>], undefined>,
  'setPayPalConfig' : ActorMethod<
    [string, string, string, boolean, boolean],
    undefined
  >,
  'setRazorpayConfig' : ActorMethod<
    [string, string, string, boolean, boolean],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[string, string], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateContent' : ActorMethod<[Content], undefined>,
  'updateDropInClass' : ActorMethod<[DropInClass], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateResidentialCourse' : ActorMethod<[ResidentialCourse], undefined>,
  'updateRetreat' : ActorMethod<[Retreat], undefined>,
  'updateRetreatPackage' : ActorMethod<
    [string, Array<RetreatPackage>],
    undefined
  >,
  'updateRetreatWithPackages' : ActorMethod<[RetreatWithPackages], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
  'updateVideoCourse' : ActorMethod<[VideoCourse], undefined>,
  'verifyPayPalPayment' : ActorMethod<[string], PayPalVerificationResponse>,
  'verifyRazorpayPayment' : ActorMethod<
    [string, string],
    RazorpayVerificationResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];