/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RazorpayConfig {
    testMode: boolean;
    enabled: boolean;
    apiKey: string;
    apiSecret: string;
    callbackUrl: string;
}
export interface VideoCourse {
    id: string;
    title: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    videoFiles: Array<ExternalBlob>;
}
export interface Product {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PayPalPaymentResponse {
    error?: string;
    paymentId?: string;
    success: boolean;
}
export interface UserProfile {
    name: string;
    purchaseHistory: Array<string>;
    email: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RetreatWithPackages {
    id: string;
    title: string;
    duration: string;
    ctaWhatsapp: string;
    endDate: bigint;
    packages: Array<RetreatPackage>;
    isCustomizable: boolean;
    hasRecurringDates: boolean;
    overview: string;
    description: string;
    inclusions: string;
    ctaBook: string;
    image: ExternalBlob;
    location: string;
    itinerary: string;
    startDate: bigint;
}
export interface Testimonial {
    id: string;
    date: bigint;
    author: string;
    message: string;
    rating: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DropInClass {
    id: string;
    instructor: string;
    name: string;
    time: bigint;
    level: string;
    durationMinutes: bigint;
    currency: string;
    price: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Booking {
    id: string;
    status: string;
    itemId: string;
    userId: Principal;
    bookingDate: bigint;
    currency: string;
    itemType: string;
    amount: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ContactInfo {
    googleBusinessLink: string;
    socialLinks: {
        instagram: string;
        facebook: string;
        youtube: string;
    };
    whatsapp: string;
    googleMapsLink: string;
    email: string;
    address: string;
    phone: string;
}
export interface Content {
    id: string;
    media: ExternalBlob;
    contentType: string;
    value: string;
    page: string;
}
export interface Retreat {
    id: string;
    title: string;
    endDate: bigint;
    description: string;
    availability: bigint;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    startDate: bigint;
}
export interface RazorpayPaymentRequest {
    receipt: string;
    currency: string;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RetreatPackage {
    description: string;
    currency: string;
    price: bigint;
    roomType: string;
}
export interface PayPalConfig {
    clientId: string;
    testMode: boolean;
    enabled: boolean;
    callbackUrl: string;
    clientSecret: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface PayPalVerificationResponse {
    error?: string;
    success: boolean;
    transactionId?: string;
}
export interface ResidentialCourse {
    id: string;
    isPrivateAvailable: boolean;
    name: string;
    description: string;
    currency: string;
    monthlyDates: Array<string>;
    image: ExternalBlob;
    price: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RazorpayVerificationResponse {
    error?: string;
    paymentId?: string;
    success: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContent(contentItem: Content): Promise<void>;
    addDropInClass(dropInClass: DropInClass): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addResidentialCourse(course: ResidentialCourse): Promise<void>;
    addRetreat(retreat: Retreat): Promise<void>;
    addRetreatPackage(retreatId: string, packages: Array<RetreatPackage>): Promise<void>;
    addRetreatWithPackages(retreatWithPackagesData: RetreatWithPackages): Promise<void>;
    addTestimonial(testimonial: Testimonial): Promise<void>;
    addVideoCourse(videoCourse: VideoCourse): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookDropInClass(booking: Booking): Promise<void>;
    bookRetreat(booking: Booking): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPayPalPaymentRequest(_items: Array<string>, amount: bigint, returnUrl: string): Promise<PayPalPaymentResponse>;
    createRazorpayPaymentRequest(_items: Array<string>, amount: bigint, currency: string, returnUrl: string): Promise<RazorpayPaymentRequest>;
    deleteContent(contentId: string): Promise<void>;
    deleteDropInClass(dropInClassId: string): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    deleteResidentialCourse(courseId: string): Promise<void>;
    deleteRetreat(retreatId: string): Promise<void>;
    deleteRetreatPackage(retreatId: string): Promise<void>;
    deleteRetreatWithPackages(retreatId: string): Promise<void>;
    deleteTestimonial(id: string): Promise<void>;
    deleteVideoCourse(videoCourseId: string): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllRetreatsWithPackages(): Promise<Array<RetreatWithPackages>>;
    getBookingsByUser(userId: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactInfo(): Promise<ContactInfo | null>;
    getContentByPage(page: string): Promise<Array<Content>>;
    getDropInClasses(): Promise<Array<DropInClass>>;
    getHomePageFeaturedRetreats(): Promise<Array<Retreat>>;
    getPayPalConfig(): Promise<PayPalConfig | null>;
    getProducts(): Promise<Array<Product>>;
    getRazorpayConfig(): Promise<RazorpayConfig | null>;
    getResidentialCourses(): Promise<Array<ResidentialCourse>>;
    getRetreatPackages(): Promise<Array<[string, Array<RetreatPackage>]>>;
    getRetreatWithPackages(id: string): Promise<RetreatWithPackages | null>;
    getRetreats(): Promise<Array<Retreat>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoCourses(): Promise<Array<VideoCourse>>;
    isCallerAdmin(): Promise<boolean>;
    isPayPalEnabled(): Promise<boolean>;
    isRazorpayEnabled(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    purchaseProduct(booking: Booking): Promise<void>;
    purchaseVideoCourse(booking: Booking): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setFeaturedRetreats(retreatIds: Array<string>): Promise<void>;
    setPayPalConfig(clientId: string, clientSecret: string, callbackUrl: string, enabled: boolean, testMode: boolean): Promise<void>;
    setRazorpayConfig(apiKey: string, apiSecret: string, callbackUrl: string, enabled: boolean, testMode: boolean): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingStatus(bookingId: string, status: string): Promise<void>;
    updateContactInfo(info: ContactInfo): Promise<void>;
    updateContent(contentItem: Content): Promise<void>;
    updateDropInClass(dropInClass: DropInClass): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateResidentialCourse(course: ResidentialCourse): Promise<void>;
    updateRetreat(retreat: Retreat): Promise<void>;
    updateRetreatPackage(retreatId: string, packages: Array<RetreatPackage>): Promise<void>;
    updateRetreatWithPackages(retreatWithPackagesData: RetreatWithPackages): Promise<void>;
    updateTestimonial(testimonial: Testimonial): Promise<void>;
    updateVideoCourse(videoCourse: VideoCourse): Promise<void>;
    verifyPayPalPayment(paymentId: string): Promise<PayPalVerificationResponse>;
    verifyRazorpayPayment(paymentId: string, signature: string): Promise<RazorpayVerificationResponse>;
}
import type { ContactInfo as _ContactInfo, Content as _Content, ExternalBlob as _ExternalBlob, PayPalConfig as _PayPalConfig, PayPalPaymentResponse as _PayPalPaymentResponse, PayPalVerificationResponse as _PayPalVerificationResponse, Product as _Product, RazorpayConfig as _RazorpayConfig, RazorpayVerificationResponse as _RazorpayVerificationResponse, ResidentialCourse as _ResidentialCourse, Retreat as _Retreat, RetreatPackage as _RetreatPackage, RetreatWithPackages as _RetreatWithPackages, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, VideoCourse as _VideoCourse, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContent(arg0: Content): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContent(await to_candid_Content_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContent(await to_candid_Content_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDropInClass(arg0: DropInClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDropInClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDropInClass(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addResidentialCourse(arg0: ResidentialCourse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResidentialCourse(await to_candid_ResidentialCourse_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResidentialCourse(await to_candid_ResidentialCourse_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRetreat(arg0: Retreat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetreat(await to_candid_Retreat_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetreat(await to_candid_Retreat_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRetreatPackage(arg0: string, arg1: Array<RetreatPackage>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetreatPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetreatPackage(arg0, arg1);
            return result;
        }
    }
    async addRetreatWithPackages(arg0: RetreatWithPackages): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetreatWithPackages(await to_candid_RetreatWithPackages_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetreatWithPackages(await to_candid_RetreatWithPackages_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async addVideoCourse(arg0: VideoCourse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoCourse(await to_candid_VideoCourse_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoCourse(await to_candid_VideoCourse_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookDropInClass(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookDropInClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookDropInClass(arg0);
            return result;
        }
    }
    async bookRetreat(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookRetreat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookRetreat(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPayPalPaymentRequest(arg0: Array<string>, arg1: bigint, arg2: string): Promise<PayPalPaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayPalPaymentRequest(arg0, arg1, arg2);
                return from_candid_PayPalPaymentResponse_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayPalPaymentRequest(arg0, arg1, arg2);
            return from_candid_PayPalPaymentResponse_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRazorpayPaymentRequest(arg0: Array<string>, arg1: bigint, arg2: string, arg3: string): Promise<RazorpayPaymentRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayPaymentRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayPaymentRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContent(arg0);
            return result;
        }
    }
    async deleteDropInClass(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDropInClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDropInClass(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteResidentialCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResidentialCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResidentialCourse(arg0);
            return result;
        }
    }
    async deleteRetreat(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRetreat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRetreat(arg0);
            return result;
        }
    }
    async deleteRetreatPackage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRetreatPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRetreatPackage(arg0);
            return result;
        }
    }
    async deleteRetreatWithPackages(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRetreatWithPackages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRetreatWithPackages(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async deleteVideoCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoCourse(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllRetreatsWithPackages(): Promise<Array<RetreatWithPackages>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRetreatsWithPackages();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRetreatsWithPackages();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentByPage(arg0: string): Promise<Array<Content>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentByPage(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentByPage(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDropInClasses(): Promise<Array<DropInClass>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDropInClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDropInClasses();
            return result;
        }
    }
    async getHomePageFeaturedRetreats(): Promise<Array<Retreat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePageFeaturedRetreats();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePageFeaturedRetreats();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayPalConfig(): Promise<PayPalConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayPalConfig();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayPalConfig();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRazorpayConfig(): Promise<RazorpayConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRazorpayConfig();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRazorpayConfig();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentialCourses(): Promise<Array<ResidentialCourse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentialCourses();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentialCourses();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetreatPackages(): Promise<Array<[string, Array<RetreatPackage>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetreatPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetreatPackages();
            return result;
        }
    }
    async getRetreatWithPackages(arg0: string): Promise<RetreatWithPackages | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetreatWithPackages(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetreatWithPackages(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetreats(): Promise<Array<Retreat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetreats();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetreats();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoCourses(): Promise<Array<VideoCourse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoCourses();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoCourses();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPayPalEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPayPalEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPayPalEnabled();
            return result;
        }
    }
    async isRazorpayEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRazorpayEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRazorpayEnabled();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async purchaseProduct(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseProduct(arg0);
            return result;
        }
    }
    async purchaseVideoCourse(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseVideoCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseVideoCourse(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setFeaturedRetreats(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeaturedRetreats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeaturedRetreats(arg0);
            return result;
        }
    }
    async setPayPalConfig(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPayPalConfig(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPayPalConfig(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setRazorpayConfig(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayConfig(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayConfig(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, arg1);
            return result;
        }
    }
    async updateContactInfo(arg0: ContactInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0);
            return result;
        }
    }
    async updateContent(arg0: Content): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(await to_candid_Content_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(await to_candid_Content_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDropInClass(arg0: DropInClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDropInClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDropInClass(arg0);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateResidentialCourse(arg0: ResidentialCourse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResidentialCourse(await to_candid_ResidentialCourse_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResidentialCourse(await to_candid_ResidentialCourse_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRetreat(arg0: Retreat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetreat(await to_candid_Retreat_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetreat(await to_candid_Retreat_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRetreatPackage(arg0: string, arg1: Array<RetreatPackage>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetreatPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetreatPackage(arg0, arg1);
            return result;
        }
    }
    async updateRetreatWithPackages(arg0: RetreatWithPackages): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetreatWithPackages(await to_candid_RetreatWithPackages_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetreatWithPackages(await to_candid_RetreatWithPackages_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0);
            return result;
        }
    }
    async updateVideoCourse(arg0: VideoCourse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoCourse(await to_candid_VideoCourse_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoCourse(await to_candid_VideoCourse_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyPayPalPayment(arg0: string): Promise<PayPalVerificationResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPayPalPayment(arg0);
                return from_candid_PayPalVerificationResponse_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPayPalPayment(arg0);
            return from_candid_PayPalVerificationResponse_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyRazorpayPayment(arg0: string, arg1: string): Promise<RazorpayVerificationResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRazorpayPayment(arg0, arg1);
                return from_candid_RazorpayVerificationResponse_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRazorpayPayment(arg0, arg1);
            return from_candid_RazorpayVerificationResponse_n59(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Content_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Content): Promise<Content> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PayPalPaymentResponse_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayPalPaymentResponse): PayPalPaymentResponse {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PayPalVerificationResponse_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayPalVerificationResponse): PayPalVerificationResponse {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_RazorpayVerificationResponse_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RazorpayVerificationResponse): RazorpayVerificationResponse {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ResidentialCourse_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentialCourse): Promise<ResidentialCourse> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_RetreatWithPackages_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetreatWithPackages): Promise<RetreatWithPackages> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Retreat_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Retreat): Promise<Retreat> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoCourse_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoCourse): Promise<VideoCourse> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactInfo]): ContactInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PayPalConfig]): PayPalConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RazorpayConfig]): RazorpayConfig | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RetreatWithPackages]): Promise<RetreatWithPackages | null> {
    return value.length === 0 ? null : await from_candid_RetreatWithPackages_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    paymentId: [] | [string];
    success: boolean;
}): {
    error?: string;
    paymentId?: string;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.error)),
        paymentId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.paymentId)),
        success: value.success
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: string;
    ctaWhatsapp: string;
    endDate: bigint;
    packages: Array<_RetreatPackage>;
    isCustomizable: boolean;
    hasRecurringDates: boolean;
    overview: string;
    description: string;
    inclusions: string;
    ctaBook: string;
    image: _ExternalBlob;
    location: string;
    itinerary: string;
    startDate: bigint;
}): Promise<{
    id: string;
    title: string;
    duration: string;
    ctaWhatsapp: string;
    endDate: bigint;
    packages: Array<RetreatPackage>;
    isCustomizable: boolean;
    hasRecurringDates: boolean;
    overview: string;
    description: string;
    inclusions: string;
    ctaBook: string;
    image: ExternalBlob;
    location: string;
    itinerary: string;
    startDate: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        ctaWhatsapp: value.ctaWhatsapp,
        endDate: value.endDate,
        packages: value.packages,
        isCustomizable: value.isCustomizable,
        hasRecurringDates: value.hasRecurringDates,
        overview: value.overview,
        description: value.description,
        inclusions: value.inclusions,
        ctaBook: value.ctaBook,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        location: value.location,
        itinerary: value.itinerary,
        startDate: value.startDate
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: _ExternalBlob;
    contentType: string;
    value: string;
    page: string;
}): Promise<{
    id: string;
    media: ExternalBlob;
    contentType: string;
    value: string;
    page: string;
}> {
    return {
        id: value.id,
        media: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.media),
        contentType: value.contentType,
        value: value.value,
        page: value.page
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    endDate: bigint;
    description: string;
    availability: bigint;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
    startDate: bigint;
}): Promise<{
    id: string;
    title: string;
    endDate: bigint;
    description: string;
    availability: bigint;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    startDate: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        availability: value.availability,
        currency: value.currency,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        price: value.price,
        startDate: value.startDate
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        currency: value.currency,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isPrivateAvailable: boolean;
    name: string;
    description: string;
    currency: string;
    monthlyDates: Array<string>;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    isPrivateAvailable: boolean;
    name: string;
    description: string;
    currency: string;
    monthlyDates: Array<string>;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        isPrivateAvailable: value.isPrivateAvailable,
        name: value.name,
        description: value.description,
        currency: value.currency,
        monthlyDates: value.monthlyDates,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
    videoFiles: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    videoFiles: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        currency: value.currency,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        price: value.price,
        videoFiles: await from_candid_vec_n56(_uploadFile, _downloadFile, value.videoFiles)
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
    transactionId: [] | [string];
}): {
    error?: string;
    success: boolean;
    transactionId?: string;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.error)),
        success: value.success,
        transactionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n52(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RetreatWithPackages>): Promise<Array<RetreatWithPackages>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RetreatWithPackages_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Content>): Promise<Array<Content>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Content_n36(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Retreat>): Promise<Array<Retreat>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Retreat_n39(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n43(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResidentialCourse>): Promise<Array<ResidentialCourse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ResidentialCourse_n47(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoCourse>): Promise<Array<VideoCourse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoCourse_n54(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, x)));
}
async function to_candid_Content_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Content): Promise<_Content> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Product_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ResidentialCourse_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentialCourse): Promise<_ResidentialCourse> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_RetreatWithPackages_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetreatWithPackages): Promise<_RetreatWithPackages> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_Retreat_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Retreat): Promise<_Retreat> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function to_candid_VideoCourse_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCourse): Promise<_VideoCourse> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        currency: value.currency,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isPrivateAvailable: boolean;
    name: string;
    description: string;
    currency: string;
    monthlyDates: Array<string>;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    isPrivateAvailable: boolean;
    name: string;
    description: string;
    currency: string;
    monthlyDates: Array<string>;
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        isPrivateAvailable: value.isPrivateAvailable,
        name: value.name,
        description: value.description,
        currency: value.currency,
        monthlyDates: value.monthlyDates,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    endDate: bigint;
    description: string;
    availability: bigint;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    startDate: bigint;
}): Promise<{
    id: string;
    title: string;
    endDate: bigint;
    description: string;
    availability: bigint;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
    startDate: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        availability: value.availability,
        currency: value.currency,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price,
        startDate: value.startDate
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: string;
    ctaWhatsapp: string;
    endDate: bigint;
    packages: Array<RetreatPackage>;
    isCustomizable: boolean;
    hasRecurringDates: boolean;
    overview: string;
    description: string;
    inclusions: string;
    ctaBook: string;
    image: ExternalBlob;
    location: string;
    itinerary: string;
    startDate: bigint;
}): Promise<{
    id: string;
    title: string;
    duration: string;
    ctaWhatsapp: string;
    endDate: bigint;
    packages: Array<_RetreatPackage>;
    isCustomizable: boolean;
    hasRecurringDates: boolean;
    overview: string;
    description: string;
    inclusions: string;
    ctaBook: string;
    image: _ExternalBlob;
    location: string;
    itinerary: string;
    startDate: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        ctaWhatsapp: value.ctaWhatsapp,
        endDate: value.endDate,
        packages: value.packages,
        isCustomizable: value.isCustomizable,
        hasRecurringDates: value.hasRecurringDates,
        overview: value.overview,
        description: value.description,
        inclusions: value.inclusions,
        ctaBook: value.ctaBook,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        location: value.location,
        itinerary: value.itinerary,
        startDate: value.startDate
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    currency: string;
    image: ExternalBlob;
    price: bigint;
    videoFiles: Array<ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    currency: string;
    image: _ExternalBlob;
    price: bigint;
    videoFiles: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        currency: value.currency,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price,
        videoFiles: await to_candid_vec_n21(_uploadFile, _downloadFile, value.videoFiles)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: ExternalBlob;
    contentType: string;
    value: string;
    page: string;
}): Promise<{
    id: string;
    media: _ExternalBlob;
    contentType: string;
    value: string;
    page: string;
}> {
    return {
        id: value.id,
        media: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.media),
        contentType: value.contentType,
        value: value.value,
        page: value.page
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
